import { describe, expect, it } from 'bun:test'
import { keccak256, toHex } from 'viem'
import {
  ACCOUNT_LIST_MANAGER,
  DEFAULT_ADMIN_ROLE,
  FEE_MANAGER_DISPATCH_ERC20,
  FEE_MANAGER_REDEEM_VEHICLE_SHARES,
  FEE_MANAGER_SET_FEES,
  FEE_MANAGER_SET_FEE_RECIPIENTS,
  MULTI_VEHICLE_DEPOSIT,
  MULTI_VEHICLE_DISPATCH,
  MULTI_VEHICLE_FEED_QUERY_REDEEM_QUEUE,
  MULTI_VEHICLE_MOVE_ASSETS,
  MULTI_VEHICLE_MOVE_SHARES,
  MULTI_VEHICLE_PROGRESS_QUERY,
  MULTI_VEHICLE_REBALANCE,
  MULTI_VEHICLE_RETRIEVE_QUERY_REDEEM_QUEUE_ASSETS,
  MULTI_VEHICLE_SET_QUEUES,
  MULTI_VEHICLE_SET_THRESHOLDS,
  MULTI_VEHICLE_SET_VEHICLE_AUTHORIZATION,
  VEHICLE_ALLOW,
  VEHICLE_SET_INTERCEPTIONS,
  VEHICLE_STEAM,
} from '../src/constants/roles.js'

const ALL_ROLES = {
  VEHICLE_STEAM,
  VEHICLE_SET_INTERCEPTIONS,
  VEHICLE_ALLOW,
  FEE_MANAGER_SET_FEES,
  FEE_MANAGER_SET_FEE_RECIPIENTS,
  FEE_MANAGER_DISPATCH_ERC20,
  FEE_MANAGER_REDEEM_VEHICLE_SHARES,
  MULTI_VEHICLE_FEED_QUERY_REDEEM_QUEUE,
  MULTI_VEHICLE_RETRIEVE_QUERY_REDEEM_QUEUE_ASSETS,
  MULTI_VEHICLE_SET_QUEUES,
  MULTI_VEHICLE_SET_VEHICLE_AUTHORIZATION,
  MULTI_VEHICLE_MOVE_ASSETS,
  MULTI_VEHICLE_MOVE_SHARES,
  MULTI_VEHICLE_REBALANCE,
  MULTI_VEHICLE_DEPOSIT,
  MULTI_VEHICLE_DISPATCH,
  MULTI_VEHICLE_PROGRESS_QUERY,
  MULTI_VEHICLE_SET_THRESHOLDS,
  ACCOUNT_LIST_MANAGER,
} as const

describe('role constants', () => {
  it('DEFAULT_ADMIN_ROLE is bytes32 zero', () => {
    expect(DEFAULT_ADMIN_ROLE).toBe(
      '0x0000000000000000000000000000000000000000000000000000000000000000',
    )
  })

  it('each role is a valid 32-byte hex string', () => {
    for (const [name, role] of Object.entries(ALL_ROLES)) {
      expect(role).toMatch(/^0x[0-9a-f]{64}$/)
    }
  })

  it('each role is the keccak256 of its name', () => {
    expect(VEHICLE_STEAM).toBe(keccak256(toHex('VEHICLE_STEAM')))
    expect(VEHICLE_SET_INTERCEPTIONS).toBe(keccak256(toHex('VEHICLE_SET_INTERCEPTIONS')))
    expect(VEHICLE_ALLOW).toBe(keccak256(toHex('VEHICLE_ALLOW')))
    expect(FEE_MANAGER_SET_FEES).toBe(keccak256(toHex('FEE_MANAGER_SET_FEES')))
    expect(FEE_MANAGER_SET_FEE_RECIPIENTS).toBe(keccak256(toHex('FEE_MANAGER_SET_FEE_RECIPIENTS')))
    expect(FEE_MANAGER_DISPATCH_ERC20).toBe(keccak256(toHex('FEE_MANAGER_DISPATCH_ERC20')))
    expect(FEE_MANAGER_REDEEM_VEHICLE_SHARES).toBe(
      keccak256(toHex('FEE_MANAGER_REDEEM_VEHICLE_SHARES')),
    )
    expect(MULTI_VEHICLE_FEED_QUERY_REDEEM_QUEUE).toBe(
      keccak256(toHex('MULTI_VEHICLE_FEED_QUERY_REDEEM_QUEUE')),
    )
    expect(MULTI_VEHICLE_RETRIEVE_QUERY_REDEEM_QUEUE_ASSETS).toBe(
      keccak256(toHex('MULTI_VEHICLE_RETRIEVE_QUERY_REDEEM_QUEUE_ASSETS')),
    )
    expect(MULTI_VEHICLE_SET_QUEUES).toBe(keccak256(toHex('MULTI_VEHICLE_SET_QUEUES')))
    expect(MULTI_VEHICLE_SET_VEHICLE_AUTHORIZATION).toBe(
      keccak256(toHex('MULTI_VEHICLE_SET_VEHICLE_AUTHORIZATION')),
    )
    expect(MULTI_VEHICLE_MOVE_ASSETS).toBe(keccak256(toHex('MULTI_VEHICLE_MOVE_ASSETS')))
    expect(MULTI_VEHICLE_MOVE_SHARES).toBe(keccak256(toHex('MULTI_VEHICLE_MOVE_SHARES')))
    expect(MULTI_VEHICLE_REBALANCE).toBe(keccak256(toHex('MULTI_VEHICLE_REBALANCE')))
    expect(MULTI_VEHICLE_DEPOSIT).toBe(keccak256(toHex('MULTI_VEHICLE_DEPOSIT')))
    expect(MULTI_VEHICLE_DISPATCH).toBe(keccak256(toHex('MULTI_VEHICLE_DISPATCH')))
    expect(MULTI_VEHICLE_PROGRESS_QUERY).toBe(keccak256(toHex('MULTI_VEHICLE_PROGRESS_QUERY')))
    expect(MULTI_VEHICLE_SET_THRESHOLDS).toBe(keccak256(toHex('MULTI_VEHICLE_SET_THRESHOLDS')))
    expect(ACCOUNT_LIST_MANAGER).toBe(keccak256(toHex('ACCOUNT_LIST_MANAGER')))
  })

  it('no two roles collide', () => {
    const values = Object.values(ALL_ROLES)
    const unique = new Set(values)
    expect(unique.size).toBe(values.length)
  })

  it('roles are stable across imports (snapshot)', () => {
    expect(VEHICLE_STEAM).toBe(keccak256(toHex('VEHICLE_STEAM')))
    expect(MULTI_VEHICLE_SET_QUEUES).toBe(keccak256(toHex('MULTI_VEHICLE_SET_QUEUES')))
  })
})
