export const conduitFactoryAbi = [
  {
    type: 'function',
    name: 'spawn',
    inputs: [
      {
        name: 'spawnParams',
        type: 'tuple',
        internalType: 'struct ConduitFactory.SpawnParams',
        components: [
          { name: 'name', type: 'string', internalType: 'string' },
          { name: 'symbol', type: 'string', internalType: 'string' },
          { name: 'vehicle', type: 'address', internalType: 'contract IVehicle' },
          { name: 'feeManager', type: 'address', internalType: 'contract IFeeManager' },
          { name: 'accountList', type: 'address', internalType: 'contract IAccountList' },
          { name: 'ownerRegistry', type: 'address', internalType: 'contract IOwnerRegistry' },
          {
            name: 'accessControl',
            type: 'address',
            internalType: 'contract ExternalAccessControl',
          },
          { name: 'transferMode', type: 'uint8', internalType: 'enum ConduitStructs.TransferMode' },
          { name: 'initialDepositSize', type: 'uint256', internalType: 'uint256' },
          { name: 'initialExpectedSupply', type: 'uint256', internalType: 'uint256' },
          { name: 'depositAsset', type: 'address', internalType: 'contract IERC20' },
          { name: 'querySalt', type: 'bytes32', internalType: 'bytes32' },
          { name: 'deploymentSalt', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
      { name: 'salt', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: 'conduit', type: 'address', internalType: 'contract IConduit' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'finalizeConduitDeposit',
    inputs: [{ name: 'conduit', type: 'address', internalType: 'contract IConduit' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'predictConduitDeployment',
    inputs: [
      {
        name: 'params',
        type: 'tuple',
        internalType: 'struct ConduitFactory.SpawnParams',
        components: [
          { name: 'name', type: 'string', internalType: 'string' },
          { name: 'symbol', type: 'string', internalType: 'string' },
          { name: 'vehicle', type: 'address', internalType: 'contract IVehicle' },
          { name: 'feeManager', type: 'address', internalType: 'contract IFeeManager' },
          { name: 'accountList', type: 'address', internalType: 'contract IAccountList' },
          { name: 'ownerRegistry', type: 'address', internalType: 'contract IOwnerRegistry' },
          {
            name: 'accessControl',
            type: 'address',
            internalType: 'contract ExternalAccessControl',
          },
          { name: 'transferMode', type: 'uint8', internalType: 'enum ConduitStructs.TransferMode' },
          { name: 'initialDepositSize', type: 'uint256', internalType: 'uint256' },
          { name: 'initialExpectedSupply', type: 'uint256', internalType: 'uint256' },
          { name: 'depositAsset', type: 'address', internalType: 'contract IERC20' },
          { name: 'querySalt', type: 'bytes32', internalType: 'bytes32' },
          { name: 'deploymentSalt', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isDeprecated',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ConduitDeployed',
    inputs: [
      { name: 'conduit', type: 'address', indexed: true, internalType: 'contract IConduit' },
      {
        name: 'params',
        type: 'tuple',
        indexed: false,
        internalType: 'struct ConduitFactory.SpawnParams',
        components: [
          { name: 'name', type: 'string', internalType: 'string' },
          { name: 'symbol', type: 'string', internalType: 'string' },
          { name: 'vehicle', type: 'address', internalType: 'contract IVehicle' },
          { name: 'feeManager', type: 'address', internalType: 'contract IFeeManager' },
          { name: 'accountList', type: 'address', internalType: 'contract IAccountList' },
          { name: 'ownerRegistry', type: 'address', internalType: 'contract IOwnerRegistry' },
          {
            name: 'accessControl',
            type: 'address',
            internalType: 'contract ExternalAccessControl',
          },
          { name: 'transferMode', type: 'uint8', internalType: 'enum ConduitStructs.TransferMode' },
          { name: 'initialDepositSize', type: 'uint256', internalType: 'uint256' },
          { name: 'initialExpectedSupply', type: 'uint256', internalType: 'uint256' },
          { name: 'depositAsset', type: 'address', internalType: 'contract IERC20' },
          { name: 'querySalt', type: 'bytes32', internalType: 'bytes32' },
          { name: 'deploymentSalt', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'FactoryDeprecated',
    inputs: [],
  },
  {
    type: 'error',
    name: 'FailedConduitCreation',
    inputs: [],
  },
  {
    type: 'error',
    name: 'FailedModuleInitialization',
    inputs: [{ name: 'module', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'NoPendingDeposit',
    inputs: [{ name: 'conduit', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'MissingRole',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'scope', type: 'address', internalType: 'address' },
      { name: 'caller', type: 'address', internalType: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'InsufficientAllowance',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InsufficientAssetBalance',
    inputs: [],
  },
] as const
