import { keccak256, toHex } from 'viem'

export const FACTORY_SPAWN = keccak256(toHex('FACTORY_SPAWN'))
export const FACTORY_DEPRECATE = keccak256(toHex('FACTORY_DEPRECATE'))
export const CONDUIT_SPAWN = keccak256(toHex('CONDUIT_SPAWN'))

export const ASSET_REGISTRY_SET_ASSET = keccak256(toHex('ASSET_REGISTRY_SET_ASSET'))

export const BEACON_FREEZE = keccak256(toHex('BEACON_FREEZE'))
export const BEACON_PAUSE = keccak256(toHex('BEACON_PAUSE'))
export const BEACON_UNPAUSE = keccak256(toHex('BEACON_UNPAUSE'))
export const BEACON_UPGRADE = keccak256(toHex('BEACON_UPGRADE'))

export const VEHICLE_STEAM_DEPOSIT = keccak256(toHex('VEHICLE_STEAM_DEPOSIT'))
export const VEHICLE_STEAM_REDEEM = keccak256(toHex('VEHICLE_STEAM_REDEEM'))
export const VEHICLE_SET_INTERCEPTIONS = keccak256(toHex('VEHICLE_SET_INTERCEPTIONS'))
export const VEHICLE_ALLOW = keccak256(toHex('VEHICLE_ALLOW'))
export const VEHICLE_EXEC = keccak256(toHex('VEHICLE_EXEC'))

export const CONDUIT_SET_INTERCEPTIONS = keccak256(toHex('CONDUIT_SET_INTERCEPTIONS'))

export const FEE_MANAGER_SET_FEES = keccak256(toHex('FEE_MANAGER_SET_FEES'))
export const FEE_MANAGER_SET_FEE_RECIPIENTS = keccak256(toHex('FEE_MANAGER_SET_FEE_RECIPIENTS'))
export const FEE_MANAGER_DISPATCH_ERC20 = keccak256(toHex('FEE_MANAGER_DISPATCH_ERC20'))

export const MULTI_VEHICLE_FEED_QUERY_REDEEM_QUEUE = keccak256(
  toHex('MULTI_VEHICLE_FEED_QUERY_REDEEM_QUEUE'),
)
export const MULTI_VEHICLE_RETRIEVE_QUERY_REDEEM_QUEUE_ASSETS = keccak256(
  toHex('MULTI_VEHICLE_RETRIEVE_QUERY_REDEEM_QUEUE_ASSETS'),
)
export const MULTI_VEHICLE_SET_QUEUES = keccak256(toHex('MULTI_VEHICLE_SET_QUEUES'))
export const MULTI_VEHICLE_SET_VEHICLE_AUTHORIZATION = keccak256(
  toHex('MULTI_VEHICLE_SET_VEHICLE_AUTHORIZATION'),
)
export const MULTI_VEHICLE_MOVE = keccak256(toHex('MULTI_VEHICLE_MOVE'))
export const MULTI_VEHICLE_DEPOSIT = keccak256(toHex('MULTI_VEHICLE_DEPOSIT'))
export const MULTI_VEHICLE_DISPATCH = keccak256(toHex('MULTI_VEHICLE_DISPATCH'))
export const MULTI_VEHICLE_PROGRESS_QUERY = keccak256(toHex('MULTI_VEHICLE_PROGRESS_QUERY'))
export const MULTI_VEHICLE_SET_THRESHOLDS = keccak256(toHex('MULTI_VEHICLE_SET_THRESHOLDS'))

export const JOB_LISTING_REGISTER = keccak256(toHex('JOB_LISTING_REGISTER'))
export const JOB_LISTING_UNREGISTER = keccak256(toHex('JOB_LISTING_UNREGISTER'))
export const JOB_LISTING_EXECUTE = keccak256(toHex('JOB_LISTING_EXECUTE'))

export const MODULE_MANAGER = keccak256(toHex('MODULE_MANAGER'))

export const ACCOUNT_LIST_MANAGER = keccak256(toHex('ACCOUNT_LIST_MANAGER'))
export const CONDUIT_FORCE_REDEEM = keccak256(toHex('CONDUIT_FORCE_REDEEM'))
export const CONDUIT_SET_TRANSFER_ENABLED = keccak256(toHex('CONDUIT_SET_TRANSFER_ENABLED'))
export const CONDUIT_PROCESS = keccak256(toHex('CONDUIT_PROCESS'))

export const KEEPER_ON_REPORT = keccak256(toHex('KEEPER_ON_REPORT'))

export const DEFAULT_ADMIN_ROLE =
  '0x0000000000000000000000000000000000000000000000000000000000000000' as const
