import { keccak256, toHex } from 'viem'

export const VEHICLE_STEAM = keccak256(toHex('VEHICLE_STEAM'))
export const VEHICLE_SET_INTERCEPTIONS = keccak256(toHex('VEHICLE_SET_INTERCEPTIONS'))
export const VEHICLE_ALLOW = keccak256(toHex('VEHICLE_ALLOW'))

export const FEE_MANAGER_SET_FEES = keccak256(toHex('FEE_MANAGER_SET_FEES'))
export const FEE_MANAGER_SET_FEE_RECIPIENTS = keccak256(toHex('FEE_MANAGER_SET_FEE_RECIPIENTS'))
export const FEE_MANAGER_DISPATCH_ERC20 = keccak256(toHex('FEE_MANAGER_DISPATCH_ERC20'))
export const FEE_MANAGER_REDEEM_VEHICLE_SHARES = keccak256(
  toHex('FEE_MANAGER_REDEEM_VEHICLE_SHARES'),
)

export const MULTI_VEHICLE_FEED_QUERY_REDEEM_QUEUE = keccak256(
  toHex('MULTI_VEHICLE_FEED_QUERY_REDEEM_QUEUE'),
)
export const MULTI_VEHICLE_RETRIEVE_QUERY_REDEEM_QUEUE_ASSETS = keccak256(
  toHex('MULTI_VEHICLE_RETRIEVE_QUERY_REDEEM_QUEUE_ASSETS'),
)
export const MULTI_VEHICLE_SET_QUEUES = keccak256(toHex('MULTI_VEHICLE_SET_QUEUES'))
export const MULTI_VEHICLE_SET_VEHICLE_AUTHORIZATION = keccak256(
  toHex('MULTI_VEHICLE_SET_VEHICLE_AUTHORIZATION'),
)
export const MULTI_VEHICLE_MOVE_ASSETS = keccak256(toHex('MULTI_VEHICLE_MOVE_ASSETS'))
export const MULTI_VEHICLE_MOVE_SHARES = keccak256(toHex('MULTI_VEHICLE_MOVE_SHARES'))
export const MULTI_VEHICLE_REBALANCE = keccak256(toHex('MULTI_VEHICLE_REBALANCE'))
export const MULTI_VEHICLE_DEPOSIT = keccak256(toHex('MULTI_VEHICLE_DEPOSIT'))
export const MULTI_VEHICLE_DISPATCH = keccak256(toHex('MULTI_VEHICLE_DISPATCH'))
export const MULTI_VEHICLE_PROGRESS_QUERY = keccak256(toHex('MULTI_VEHICLE_PROGRESS_QUERY'))
export const MULTI_VEHICLE_SET_THRESHOLDS = keccak256(toHex('MULTI_VEHICLE_SET_THRESHOLDS'))

export const ACCOUNT_LIST_MANAGER = keccak256(toHex('ACCOUNT_LIST_MANAGER'))
