import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getAddress } from 'viem'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const CONTRACTS_DIR = process.argv[2] || resolve(scriptDir, '../../contracts')
const CONTRACTS_DEPLOYMENTS = resolve(CONTRACTS_DIR, 'deployments')
const SDK_ADDRESSES = resolve(scriptDir, '../src/contracts/addresses.ts')

const DEPLOYMENTS: Record<number, string> = {
  8453: 'base_testnet.json',
  1: 'mainnet_testnet.json',
}

// Not deployed by contracts, so absent from its deployment files: USDC is Circle's and the
// PoolAddressesProvider is Aave's. Both transcribed from the contracts repo's fork configs —
// test/forks/vehicles/aave_v3/AaveV3VehicleForkConfig.sol.
const EXTERNAL: Record<number, { usdc: string; aavePoolAddressesProvider: string }> = {
  8453: {
    usdc: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    aavePoolAddressesProvider: '0xe20fCBdBfFC4Dd138cE8b2E6FBb6CB49777ad64D',
  },
  1: {
    usdc: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    aavePoolAddressesProvider: '0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e',
  },
}

type Deployment = {
  metadata: { chainId: number; slug: string }
  admin: Record<string, string>
  factories: Record<string, string>
  instances: Record<string, string>
}

function resolveAddresses(deployment: Deployment, chainId: number) {
  const { factories, admin, instances } = deployment
  const external = EXTERNAL[chainId]
  if (!external) {
    throw new Error(`No external addresses known for chain ${chainId}`)
  }

  return {
    conduitFactory: factories.ConduitFactory,
    coreFactory: factories.CoreFactory,
    multiVehicleFactory: factories.MultiVehicleFactory,
    aaveV3VehicleFactory: factories.AaveV3VehicleFactory,
    erc4626VehicleFactory: factories.ERC4626VehicleFactory,
    morphoBlueVehicleFactory: factories.MorphoBlueVehicleFactory,
    wrapperVehicleFactory: factories.WrapperVehicleFactory,
    eacFactory: factories.AccessControlFactory,
    adminEac: admin.AdminExternalAccessControl,
    feeManagerFactory: factories.FeeManagerFactory,
    modulesManagerFactory: factories.ModulesManagerFactory,
    accountListFactory: factories.AccountListFactory,
    ownerRegistryFactory: factories.OwnerRegistryFactory,
    assetRegistry: factories.AssetRegistry,
    queryRegistry: instances.QueryRegistry,
    aavePoolAddressesProvider: external.aavePoolAddressesProvider,
    usdc: external.usdc,
  }
}

if (!existsSync(CONTRACTS_DEPLOYMENTS)) {
  console.error(`Error: contracts deployments not found at ${CONTRACTS_DEPLOYMENTS}`)
  console.error('Usage: bun scripts/sync-addresses.ts [path-to-contracts]')
  process.exit(1)
}

const blocks: string[] = []

for (const [chainId, fileName] of Object.entries(DEPLOYMENTS)) {
  const sourceFile = resolve(CONTRACTS_DEPLOYMENTS, fileName)
  if (!existsSync(sourceFile)) {
    console.error(`Error: ${fileName} not found in ${CONTRACTS_DEPLOYMENTS}`)
    process.exit(1)
  }

  const deployment: Deployment = JSON.parse(readFileSync(sourceFile, 'utf8'))
  if (deployment.metadata.chainId !== Number(chainId)) {
    console.error(
      `Error: ${fileName} declares chainId ${deployment.metadata.chainId}, expected ${chainId}`,
    )
    process.exit(1)
  }

  const resolved = resolveAddresses(deployment, Number(chainId))
  const missing = Object.entries(resolved).filter(([, address]) => !address)
  if (missing.length > 0) {
    console.error(`Error: ${fileName} is missing ${missing.map(([key]) => key).join(', ')}`)
    process.exit(1)
  }

  const entries = Object.entries(resolved)
    .map(([key, address]) => `    ${key}: '${getAddress(address)}',`)
    .join('\n')

  blocks.push(
    `  // contracts deployments/${fileName} (slug ${deployment.metadata.slug})\n  ${chainId}: {\n${entries}\n  },`,
  )
  console.log(`✅ chain ${chainId} <- ${fileName} (slug ${deployment.metadata.slug})`)
}

writeFileSync(
  SDK_ADDRESSES,
  `import type { Address } from 'viem'

export type ChainAddresses = {
  conduitFactory: Address
  coreFactory: Address
  multiVehicleFactory: Address
  aaveV3VehicleFactory: Address
  erc4626VehicleFactory: Address
  morphoBlueVehicleFactory: Address
  wrapperVehicleFactory: Address
  eacFactory: Address
  adminEac: Address
  feeManagerFactory: Address
  modulesManagerFactory: Address
  accountListFactory: Address
  ownerRegistryFactory: Address
  assetRegistry: Address
  queryRegistry: Address
  aavePoolAddressesProvider: Address
  usdc: Address
}

// Generated by scripts/sync-addresses.ts — run \`bun run addresses:sync\` to regenerate.
export const addresses = {
${blocks.join('\n')}
} as const satisfies Record<number, ChainAddresses>

export type SupportedChainId = keyof typeof addresses
`,
)

console.log(`\nWrote ${blocks.length} chains to src/contracts/addresses.ts`)
